menu:
  Home: /
  Archives: /archives
  About: /about/
#If you dont want it, just comment it out
# weibo: yourweibo
github: https://git.io/T
# linkedin: yourlinkedin
email: mailto:you1474600@gmail.com
twitter: https://twitter.com/you06v

#Put into /source
avator: /avatar.jpg
license: /assets/by-nc.svg
